### ISSUE TITLE
weird files selection when using Shift+arrow keys

### ISSUE THREAD

**Issue by sandrotosi** [sandrotosi/puddletag#11]
1. Say you have 4 files in the files list view; file1..file4
2. right click on file1
3. now hold Shift and enter down arrow
4. the expected file selection should be file1,file2; in reality is file1,file3 (you can check by either "Play" the selection, or looking at what lines are highlighted); pressing Shift+Down again, it will select file1,file3,file4 so skipping file2 consistently

even weirder if you start from file4 and Shit+Up: the _unselected_ file shifts, always being the one right below the top selected file

**Comment by Arnvidr** [comment]
The same seems to occur when clicking on file1, then shift+clicking on file4. file2 remains unselected, even though the column I used for clicking (and only that column) have all lines selected, in a different colour than the actual selections. See picture.

![selection](https://user-images.githubusercontent.com/44213979/83106711-395ed200-a0bd-11ea-8c67-0029a35a01d8.png)
