### ISSUE TITLE
`sorted` with old P2 argument `cmp` instead of `key`

### ISSUE THREAD

**Issue by pedrobaeza** [sandrotosi/puddletag#15]
There are several places where the `sorted` method is used using the old `cmp` argument. I have found for example when opening extended tags dialog.

I can provide a patch sorting this out, but I have seen that @sandrotosi has already touch a bit code involved in class compare in puddleobjects.py, so I don't want to mix the work.

**Comment by sandrotosi** [comment]
go ahead and submit a PR @pedrobaeza ! I've just fixed it in the places where i needed to fix other crashes or misbehavior, and i have a TODO item to fix, please do beat me to it :)
