### ISSUE TITLE
configobj and PyQt5 modules not found while they're installed [Ubuntu 20.04]

### ISSUE THREAD

**Issue by Fenyx93** [sandrotosi/puddletag#29]
I've installed it as described in the included README file
"Alternatively, install it by running python setup.py install as root in the unzipped directory."

```
$ puddletag
Error: The configobj module wasn't found. Please check that it's installed properly. Download it from your distro's repository (usually python-configobj) or directly from http://code.google.com/p/configobj/ 

Error: The PyQt5 module wasn't found. Please check that it's installed properly. Download it from your distro's repository (python-qt5 usually) or directly from http://www.riverbankcomputing.co.uk/software/pyqt/intro

$ sudo apt install python3 python3-six python3-mutagen python3-configobj python3-pyparsing python3-pyqt5 python3-pyqt5.qtsvg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-configobj is already the newest version (5.0.6-4).
python3-pyparsing is already the newest version (2.4.6-1).
python3-six is already the newest version (1.14.0-2).
python3-pyqt5 is already the newest version (5.14.1+dfsg-3build1).
python3-pyqt5.qtsvg is already the newest version (5.14.1+dfsg-3build1).
python3-mutagen is already the newest version (1.44.0+2-0~ppa2~focal).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -r
5.4.0-37-generic
```

**Comment by sandrotosi** [comment]
> I've installed it as described in the included README file
> "Alternatively, install it by running python setup.py install as root in the unzipped directory."

what readme (there are 2..)? pretty sure you're looking at the wrong one: read https://github.com/sandrotosi/puddletag

> 
> ```
> $ puddletag
> Error: The configobj module wasn't found. Please check that it's installed properly. Download it from your distro's repository (usually python-configobj) or directly from http://code.google.com/p/configobj/ 

what is the full path of puddletag? pretty sure you're not following the right instructions

**Comment by Fenyx93** [comment]
At first, thanks for your reactivity.
I've followed the instructions located in /puddletag/source/README.

The full path of puddletag on my system:
```
$ which puddletag
/usr/local/bin/puddletag
```

**Comment by sandrotosi** [comment]
please follow the instructions at https://github.com/sandrotosi/puddletag/blob/pyqt5%2Bpy3/README.md

**Comment by Fenyx93** [comment]
> please follow the instructions at https://github.com/sandrotosi/puddletag/blob/pyqt5%2Bpy3/README.md

Yes, it's the same instructions that I've followed so I already did this steps, as you can see below.

Prerequisites already installed :
```
$ sudo apt install python3 python3-mutagen python3-configobj python3-pyparsing python3-pyqt5 python3-pyqt5.qtsvg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-configobj is already the newest version (5.0.6-4).
python3-pyparsing is already the newest version (2.4.6-1).
python3-pyqt5 is already the newest version (5.14.1+dfsg-3build1).
python3-pyqt5.qtsvg is already the newest version (5.14.1+dfsg-3build1).
python3-mutagen is already the newest version (1.44.0+2-0~ppa2~focal).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
Then:
```
git clone https://github.com/sandrotosi/puddletag ~/git/puddletag
cd ~/git/puddletag
PYTHONPATH=source/ ./source/puddletag
python setup.py --help-commands
sudo python setup.py install

[Source: history command]
```

**Comment by sandrotosi** [comment]
you should have stopped at

```
$ git clone https://github.com/sandrotosi/puddletag ~/git/puddletag
$ cd ~/git/puddletag
$ PYTHONPATH=source/ ./source/puddletag
```

was puddletag not working already at this point?

**Comment by sandrotosi** [comment]
also never ever run this:

```$ sudo python setup.py install```

if you dont know exactly what your doing and how to revert/fix what gets broken.

always install local to your user

please also not that `python` is still python2, so how can you expect to run puddletag from my repo (which is only python3) when you install it via python2?

**Comment by Fenyx93** [comment]
> you should have stopped at
> 
> ```
> $ git clone https://github.com/sandrotosi/puddletag ~/git/puddletag
> $ cd ~/git/puddletag
> $ PYTHONPATH=source/ ./source/puddletag
> ```
> 
> was puddletag not working already at this point?

Yes but I didn't want to start it this way each time I needed it. I wanted to use it as I did before, by a right click on my mp3 file > open with > puddletag. That's why I've followed your "alternative" instructions.

**Comment by sandrotosi** [comment]
was the warning at the top of the readme not explicit enough: "WARNING: this is a development branch to update puddletag to PyQt5 and Python3; expect bugs, if so report them in the issues session of github."

this is not meant to be used "as it was before", this is purely for development and bug reporting.

**Comment by Fenyx93** [comment]
> also never ever run this:
> 
> `$ sudo python setup.py install`
> 
> if you dont know exactly what your doing and how to revert/fix what gets broken.
> 
> always install local to your user
> 
> please also not that `python` is still python2, so how can you expect to run puddletag from my repo (which is only python3) when you install it via python2?

I thought instructions were here to show me what to do the proper way, as it usually is. Your instructions explain to run python setup.py AS ROOT, not python3. So I've started the installation just as explained with sudo. I've added the `--install` argument just because running `sudo python setup.py` did nothing but telling me that an argument was missing. And it worked, I can find the puddletag icon in the apps menu as expected. 


> if you dont know exactly what your doing and how to revert/fix what gets broken.

Didn't know it was instructions for experts as puddletag isn't an application dedicated to experts. I've just followed what I've read. Sorry for my lack of knowledge but I've found it pretty logical.

**Comment by Fenyx93** [comment]
> expect bugs, if so report them in the issues session of github
Yup, that's what I'm doin' here.

> this is not meant to be used "as it was before"
"- install it by running python setup.py install as root in the unzipped directory.
- puddletag should appear in your Multimedia (or Sounds etc.) menu. If not run 'desktop-file-install puddletag.desktop' as root in the unzipped directory."
It was like this before, I just needed a .desktop file to do what I need. We could play with words for ever, but I don't see the point of adding these instructions if I can't follow it.

**Comment by Fenyx93** [comment]
Closing the issue isn't of any help to understand a way to resolve the problem. Anyway, even if your answer was full of condescension, thank you for taking the time to answer.

**Comment by Fenyx93** [comment]
Finally resolved.

> also never ever run *** if you dont know exactly what your doing and how to revert/fix what gets broken.

1/ After some researches I've done voluntarily again the exact same wrong install with `$ sudo python setup.py install` instead of using python3, but adding ` --record installation.log` at the end of the command. So I could remove the first wrong installation properly with `cat installation.log | xargs sudo rm -rf`.
.

> note that python is still python2, so how can you expect to run puddletag from my repo (which is only python3) when you install it via python2?

2/ Then I did again the same installation but this time with python3 command:
```
sudo python3 setup.py install --record installation.log
sudo desktop-file-install puddletag.desktop
```
> this is not meant to be used "as it was before"

Now it works fine and I can use puddletag the way I did before (even if some peoples don't like this concept).

A noob isn't so newbie anymore if we take the time to explain some basics he's missing. It's a part of the FOSS community's state of mind, any expert has been a noob before :slightly_smiling_face: 

Have a nice day :+1:

**Comment by sblask** [comment]
Using sudo to install anything Python like that is generally a bad idea because that will change your system Python installation that other parts of the system rely on. A better way is to install into a virtual env and create a link in /usr/bin for example. This is how I do it in a different project: https://github.com/sblask/imsa#installation . The first two sudos are only necessary because I chose to install to /opt but you can also install into your home and then you only need sudo to create the link.
