### ISSUE TITLE
Replacement for FreeDB?

### ISSUE THREAD

**Issue by blueblots** [sandrotosi/puddletag#35]
While working on the exception in tag sources https://github.com/sandrotosi/puddletag/pull/34 I realized that freedb was shutting down in March this year and is no longer accessible for tag queries :(

But musicbrainz still seems operational so I wanted to know if there would be any interest in working on getting puddletag to query musicbrainz for tags instead of freedb.

I was going to start working on it myself, let me know if anyone is interested

**Comment by chasbro-1** [comment]
freedb has been replaced with gnudb.  See http://www.gnudb.org/

Musicbrainz would also be nice.

**Comment by klslz** [comment]
I just got it fixed, didn't have time to issue a pull request :

./source/puddlestuff/tagsources/CDDB.py

```
default_server = 'http://gnudb.gnudb.org/~cddb/cddb.cgi'
```

The API is working and seems to be full compatible. 

Did some tests. And it works.

**Comment by audiomuze** [comment]
> But musicbrainz still seems operational so I wanted to know if there would be any interest in working on getting puddletag to query musicbrainz for tags instead of freedb.

Musicbrainz has long been supported in puddletag, no reason it wouldn't be in 2.0

**Comment by klslz** [comment]
FYI. I issued a pull request #36

**Comment by klslz** [comment]
Musicbrainz support requires python-musicbrainz,  which is not available respectively fully compatible with python 3.x 
if I am not mistaken. 

I'd guess this needs further analysis and would also be a different "issue".

From my perspective this issue can be closed - as soon as my pull request is accepted.

**Comment by sandrotosi** [comment]
Fixed via #36
