### ISSUE TITLE
TagSources Discogs - Not working

### ISSUE THREAD

**Issue by klslz** [sandrotosi/puddletag#37]
I tried to lookup tags from Discogs.

I am entering a CD release id. E.g. 

https://www.discogs.com/Norah-Jones-Come-Away-With-Me/release/9262044

":r 9262044"

All I get is: 

```
An error occurred: Discogs release id should be an integer
```

Has the discogs tagsources feature been ported or looked at at all?

What would be the API key to be entered as offered in the settings submenu? I already tried  "puddletag/0.9.11"

**Comment by klslz** [comment]
I tested it manually like:

'''
curl https://api.discogs.com/releases/9262044 --user-agent "puddletag/2.0"
'''

I also learned that an API key ( as offered in the UI) is not needed by discogs.
A "user-agent" as replacement, can but hasn't have to be given though.
The related API-key field in the UI  would actually no longer be required or could be renamed to user-agent.

**Comment by klslz** [comment]
If I enter just the r_id I get this:

```
initial_value must be str or None, not bytes

```
That's a well known Python 2 3 migration issue (StringIO ByteIO)

**Comment by sandrotosi** [comment]
@klslz language such as "Has the discogs tagsources feature been ported or looked at at all?" is not helping anyone -- we are all volunteers using our spare time to develop this software. please be more mindful about how you express your thoughts, the language you're using, the possible language barrier (f.e. what gets lost in translation) and of the time and effort people put into puddletag.

**Comment by klslz** [comment]
Relax. No offense.

The freedb access - I solved earlier this week by my pull request - wasn't  working either.
It's simply not clear how the - "your" - project fork is advancing.

And yep. I am also a volunteer. And also spent hundreds of hours on stuff like this. And I am happy to contribute.

Anyhow. Your efforts are appreciated.

**Comment by klslz** [comment]
I just tested it.

Just entering the manually fetched release id from discogs did come up with the proper tags.
tags could also be applied to the tracks. Great.

I'm not sure yet how the "retrieve cover" is supposed to work. I had it ticked and nothing happened.
