### ISSUE TITLE
Proper dependencies?

### ISSUE THREAD

**Issue by uriel1998** [sandrotosi/puddletag#5]
I've cloned the repo and installed the python3 versions of the dependencies, but it's still complaining that PyQT5.QtSvg isn't findable.  If there's an updated list of what I need, I can check and make sure I've got all the right stuff already installed, please.  Thanks!

**Comment by sandrotosi** [comment]
Did you follow my instructions at https://github.com/keithgg/puddletag/issues/468 ? those are for debian, so if you use a different distribution, you're gonna have to adapt them. but anyhow, in them there's explicitly `python3-pyqt5.qtsvg` which is the Qt5 submodule for SVG management.

**Comment by uriel1998** [comment]
Got it!  Forked and included in README now for you, should be a pull request in just a few.  Thank you so much for doing this, and I hope my little contribution helps.

**Comment by sandrotosi** [comment]
that works for me, thanks! (ideally this branch, when finalized, will be merged into Keith's master branch, so i've added a warning about the in-development situation)
