### ISSUE TITLE
Unexpected behavior when writing and removing MP3 ID3 tags (Changes do not overwrite tags)

### ISSUE THREAD

**Issue by gitjade** [sandrotosi/puddletag#51]
Steps to replicate:
1. Make a change to an MP3 file, then Save (Ctrl+S)
2. Make another change to the same MP3 file, then Save (Ctrl+S)
3. Remove Tag (Ctrl+R)
4. Refresh (F5)
Result: The tags will be in the state after Step 1.
Expected result: The MP3 file should have no tags.

If you repeat step 2 multiple times, the tags stack. (i.e. Pressing Ctrl+R X times will return the MP3 tags to the state X saves ago.)

I tested changing MP3 tags with the Tag Panel, Extended Tags dialog, and the main spreadsheet panel, all with the same result. This behavior does not occur with M4A, FLAC, or OGG files, which behave as expected.

You can also confirm the unexpected behavior with ffprobe: If you erase a single field from an MP3 file (e.g. removing the song title), it will still be visible in ffprobe even though it has been "removed" from the file.

OS: Arch (puddletag-qt5-git package, pulled before making this bug report)

**Comment by pedrobaeza** [comment]
Might be related to #20

**Comment by audiomuze** [comment]
Worth checking on DSF files also. Will do and revert.

**Comment by gitjade** [comment]
Thanks for fixing this!
