### ISSUE TITLE
No Musicbrainz?

### ISSUE THREAD

**Issue by infidelus** [sandrotosi/puddletag#57]
I'm aware this is still a work-in-progress update so apologies if I'm missing something obvious but, based on the comments in the readme and another bug report I can see, I was under the impression Musicbrainz was available as a tag source in this development version.  Having just cloned the repo and tried today Musicbrainz does not appear as an available source.

The only available sources I can see are Amazon, Discogs and FreeDB.

**Comment by sandrotosi** [comment]
from what i can see [here](https://github.com/sandrotosi/puddletag/blob/pyqt5%2Bpy3/source/puddlestuff/tagsources/__init__.py#L240-L248) it looks like a tag source is only shown if we can import it properly, so likely there's something wrong in that module; i can reproduce it on my machine, so i'm gonna have a look at it

**Comment by infidelus** [comment]
Thanks for the prompt reply.  Glad it's reproducible and not just me :)

**Comment by infidelus** [comment]
Well that was quick!  Confirming Musicbrainz now shows, but also now seeing https://github.com/sandrotosi/puddletag/issues/46 when I try to search.

**Comment by sandrotosi** [comment]
hm interesting, can you share what you searched? i entered `metallica` on an empty files list and it returned results as expected

**Comment by infidelus** [comment]
It returned results correctly, but if you click on the result, that's when it errors.  I've just tried metallica then clicked CETI - Ceti plays Metallica from the list of results.  Tried Iron Maiden too, just to keep the theme going, with the same result :)

**Comment by sandrotosi** [comment]
gotcha, lemme go save metal: UP THE IRONS
