### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by ranperry** [sandrotosi/puddletag#8]
Getting this error when trying to run puddletag:

ran@vbox:~/Code/puddletag/source$ ./puddletag
puddletag Version: 2.0.0
Locale: en_CA
Traceback (most recent call last):
File "./puddletag", line 334, in
win = MainWin()
File "/home/ran/Code/puddletag/source/puddlestuff/puddletag.py", line 331, in init
menus = ls.get_menus('menu')
File "/home/ran/Code/puddletag/source/puddlestuff/loadshortcuts.py", line 49, in get_menus
menus = [(z, temp[z]) for z in settings[section + 'attrs']['order']]
KeyError: 'order'

All dependencies were resolved prior to this message. Running on Ubuntu 20.04

**Comment by sandrotosi** [comment]
can you try to rename the configuration directory (it could either be in `~/.config/puddletag` or `~/.local/config/puddletag` and try to start puddletag again? if it work, at least we know there's a setting that's causing this and can debug further

**Comment by ranperry** [comment]
I remove the conf file and it did not solve the issue. I tried to use the conf file from Mint 19.3 and it did not solve the issue. I noticed that the default conf file is pretty empty. This is the content:

{
  "puddleactions": {
    "firstrun": false,
    "convert": false
  }
}

**Comment by sandrotosi** [comment]
I just committed 5034b94d8dbfbabae5a2e173536294c43b73a3ac to log a message when you read a config file, so we know exactly what's puddletag reading.

could you re-run with the `-d` cli option and check the content of the `menus` config file (for me it's at `~/.config/puddletag/menus)? it should contain smth like `menuattrs` or `toolbarattrs` at the end (you can even post it )

**Comment by ranperry** [comment]
The latest commit solved the issue. Puddletag loads without any issues or errors! Time for some tagging. Thanks!
