### ISSUE TITLE
When loading a playlist: `TypeError: loadFiles[object, list, bool] signal has 3 argument(s) but 5 provided`

### ISSUE THREAD

**Issue by sandrotosi** [sandrotosi/puddletag#9]
File > Load playlist > select .m3u file, a pop-up will appear, but the actual underlying exception is:

```
Traceback (most recent call last):
  File "source/puddlestuff/puddletag.py", line 157, in <lambda>
    return lambda: getattr(control, command)()
  File "source/puddlestuff/puddletag.py", line 545, in loadPlayList
    self.loadFiles.emit(files, None, None, None, filename)
TypeError: loadFiles[object, list, bool] signal has 3 argument(s) but 5 provided
Aborted
```

**Comment by blueblots** [comment]
Hi I just cloned this repository yesterday and I made some changes to it that fixes this m3u playlist problem. How can I submit my changes?

**Comment by sandrotosi** [comment]
thanks @blueblots ! You need to open a PR against this repo, it looks like you opened one against your own :) i left some comments at https://github.com/blueblots/puddletag/pull/1
